version: '3'
services:
  keycloak:
    image: jboss/keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=adminpassword
      - DB_VENDOR=POSTGRES
      - DB_ADDR=keycloak-db
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=dbpassword
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - keycloak-db
    networks:
      - keycloak-network

  keycloak-db:
    image: postgres
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=dbpassword
    networks:
      - keycloak-network

networks:
  keycloak-network:
    driver: bridge
