version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=adminpassword
      - KC_DB=postgres
      - KC_DB_URL_HOST=shinyproxy-db
      - KC_DB_URL_PORT=5432
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=dbpassword
      - KC_HOSTNAME_URL=http://localhost:8080/auth
      - KC_HTTP_RELATIVE_PATH=auth
      - KC_HTTP_ENABLED=true
    ports:
      - "8443:8443"
      - "8080:8080"
    entrypoint: ["/opt/keycloak/bin/kc.sh","start"]
    depends_on:
      - shinyproxy-db
    networks:
      - keycloak-network

  shinyproxy-db:
    image: postgres
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=dbpassword
    networks:
      - keycloak-network
  
  shinyproxy:
    image: openanalytics/shinyproxy:3.0.2
    user: root
    volumes:
      - "./application.yml:/opt/shinyproxy/application.yml"
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8090:8080"
    networks:
      - keycloak-network
    depends_on:
      - keycloak

networks:
  keycloak-network:
    driver: bridge
