version: '3.8'
services:
  db:
    container_name: pg_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
       - postgres:/data/postgres
    networks:
      postgres:
        ipv4_address: 172.20.0.5
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      postgres:
        ipv4_address: 172.20.0.6
    restart: unless-stopped
    logging:
      driver: "none"
networks:
  postgres:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24

volumes:
    postgres:
    pgadmin: